evinism/mistql

README.md
js/package.json
js/src/builtins.spec.ts
js/src/builtins.ts
js/src/executor.ts
js/src/parser.spec.ts
js/src/parser.ts
js/src/types.ts

(hint: we might be able to also do this with the bar operators too)

Make dot operator into a binary operator

---

js/src/builtins/index.ts
js/src/builtins/withindices.ts
shared/testdata.json

fixes #60 by adding `#withindices`

Add withindices function

---

py/mistql/builtins.py
py/mistql/execute.py
py/mistql/expression.py
py/mistql/parse.py
py/mistql/runtime_value.py
py/mistql/stack.py
shared/testdata.json

py cleanup

---

py/mistql/builtins.py
py/mistql/exceptions.py
py/mistql/execute.py
py/mistql/parse.py
py/mistql/runtime_value.py
py/mistql/stack.py

Assertions, Exceptions, more frameworks for getting python looking pretty.

more python cleanup

---

docs/docs/reference/types.md
js/src/lexer.ts
shared/testdata.json

Along with https://github.com/evinism/mistql/pull/83, fixes https://github.com/evinism/mistql/issues/81

Make JS accept json-like numbers

---

js/src/builtins/mapkeys.ts
py/mistql/builtins.py
shared/testdata.json

Added examples as part of the test suite, also found an issue with mapkeys

More Tests

---

js/src/builtins/sum.ts
py/mistql/builtins.py
shared/testdata.json

Oversight 0.4.4 that I didn't have this in place, but what can you do but patch and bump
Also didn't have count tests so i added that in.

test and unify summing behavior

---

docs/docs/reference/functions.md
js/src/builtins/flatten.ts
js/src/builtins/index.ts
py/mistql/builtins.py
shared/testdata.json

Add flatten method to MistQL

---

.github/workflows/python.yml
py/mistql/builtins.py
py/mistql/exceptions.py
py/mistql/execute.py
py/mistql/expression.py
py/mistql/parse.py
py/poetry.lock
py/pyproject.toml
talc.yaml

mypy for python

---

py/mistql/cli.py
py/tests/test_cli.py

refactor python cli a little, add some unicode tests

---

docs/docs/reference/implementations/py.md
py/mistql/runtime_value.py
py/tests/test_gardenwall.py

correct for and allow datetime package values as input

---

js/src/builtins/sort.ts
js/src/builtins/sortby.ts
js/src/runtimeValues.ts
py/mistql/builtins.py
py/mistql/runtime_value.py
shared/testdata.json

fail on sorting single element arrays with unsortable keys

---

js/src/executor.ts
shared/testdata.json

whoops failed to add this in as an assertion.

assert returning external types fails

---

js/src/shared.spec.ts
py/tests/test_shared.py

add test skipping to js and python

---

shared/testdata.json

With our newly minted skip feature in the shared test suite, we're able to introduce a few tests that are skipped in certain implementations.

add inconsistency tests

---

js/src/builtins/indexFn.ts
js/src/builtins/regex.ts
js/src/builtins/split.ts
shared/testdata.json

Full unicode support for JS in MistQL!!

JS / Python interop with string splitting and indexing

---

js/src/builtins/indexFn.ts
shared/testdata.json

This is far more sane of an implementation

Splat to iter on strings (so we don't have to construct the whole array)

---

js/src/lexer.ts
js/src/parser.ts
js/src/perf.spec.ts

This is literally a 50x performance improvement in the parser.

attempt at non-allocating parser

---

README.md

Fixed a small typo in the readme file.

Fix_typo_in_readme

---

py/mistql/cli.py
py/poetry.lock
py/pyproject.toml

Signed-off-by: Ilan Pinto <ilpinto@redhat.com>

added jsonl support

---

py/pyproject.toml
py/uv.lock

fix(python): compatible version pins 

---

shared/testdata.json

This gives us a hint more behavioral coverage. https://github.com/evinism/mistql/issues/204 came out of this, too, so these are clearly edge cases we care about.
Lots of failing tests now, too.

fill out shared tests a little more
